# Generated by Django 4.1.2 on 2022-10-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('STORY', 'Story'), ('TASK', 'Task'), ('SUBTASK', 'Sub task')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issues.issue')),
                ('sub_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='issues.issue')),
            ],
            options={
                'unique_together': {('parent_issue', 'sub_issue')},
            },
        ),
    ]
