# Generated by Django 4.1.2 on 2022-10-22 19:24

from django.db import migrations


def create_initial_issues(apps, schema_editor):
    Issue = apps.get_model('issues', 'Issue')
    Issue.objects.create(
        summary='The very first issue',
        description='Just a dummy task',
        type='TASK',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_issues,
            reverse_code=migrations.RunPython.noop
        ),
    ]
