# Generated by Django 4.1.2 on 2022-10-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20221022_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
            preserve_default=False,
        ),
    ]
